# Generated by Django 5.0.1 on 2024-01-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0003_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
    ]
